name: Restart Bot

on:
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Restart bot on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/aftl-discord-bot
            git pull
            npm install
            pm2 restart aftl-bot
